import type { BettingMatch } from "./betting-types";

// Mock data for UI preview when backend is unavailable
export const MOCK_MATCHES: BettingMatch[] = [
  // Live matches
  {
    id: "soccer-live-1",
    sport: "soccer",
    league: "Premier League",
    status: "live",
    startTime: new Date().toISOString(),
    liveMinute: 67,
    home: {
      name: "Manchester City",
      shortName: "MCI",
      elo: 1892,
    },
    away: {
      name: "Liverpool",
      shortName: "LIV",
      elo: 1878,
    },
    score: { home: 2, away: 1 },
    odds: { home: 1.65, draw: 3.8, away: 4.5 },
    modelProb: { home: 0.58, draw: 0.24, away: 0.18 },
    pick: "home",
    edgePercent: 4.2,
    confidence: 72,
  },
  {
    id: "basketball-live-1",
    sport: "basketball",
    league: "NBA",
    status: "live",
    startTime: new Date().toISOString(),
    liveMinute: 32,
    home: {
      name: "Los Angeles Lakers",
      shortName: "LAL",
      elo: 1756,
    },
    away: {
      name: "Boston Celtics",
      shortName: "BOS",
      elo: 1812,
    },
    score: { home: 78, away: 82 },
    odds: { home: 2.1, away: 1.75 },
    modelProb: { home: 0.42, away: 0.58 },
    pick: "away",
    edgePercent: 3.8,
    confidence: 68,
  },
  {
    id: "tennis-live-1",
    sport: "tennis",
    league: "ATP Tour",
    status: "live",
    startTime: new Date().toISOString(),
    home: {
      name: "Carlos Alcaraz",
      shortName: "ALC",
      elo: 2145,
    },
    away: {
      name: "Jannik Sinner",
      shortName: "SIN",
      elo: 2138,
    },
    score: { home: 2, away: 1 },
    odds: { home: 1.85, away: 1.95 },
    modelProb: { home: 0.54, away: 0.46 },
    pick: "home",
    edgePercent: 2.1,
    confidence: 61,
  },

  // Upcoming matches
  {
    id: "soccer-upcoming-1",
    sport: "soccer",
    league: "La Liga",
    status: "upcoming",
    startTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    home: {
      name: "Real Madrid",
      shortName: "RMA",
      elo: 1905,
    },
    away: {
      name: "Barcelona",
      shortName: "BAR",
      elo: 1889,
    },
    odds: { home: 2.2, draw: 3.4, away: 3.0 },
    modelProb: { home: 0.48, draw: 0.26, away: 0.26 },
    pick: "home",
    edgePercent: 5.6,
    confidence: 78,
  },
  {
    id: "soccer-upcoming-2",
    sport: "soccer",
    league: "Bundesliga",
    status: "upcoming",
    startTime: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    home: {
      name: "Bayern Munich",
      shortName: "BAY",
      elo: 1876,
    },
    away: {
      name: "Borussia Dortmund",
      shortName: "BVB",
      elo: 1834,
    },
    odds: { home: 1.55, draw: 4.2, away: 5.5 },
    modelProb: { home: 0.64, draw: 0.22, away: 0.14 },
    pick: "home",
    edgePercent: 3.2,
    confidence: 71,
  },
  {
    id: "basketball-upcoming-1",
    sport: "basketball",
    league: "NBA",
    status: "upcoming",
    startTime: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    home: {
      name: "Golden State Warriors",
      shortName: "GSW",
      elo: 1789,
    },
    away: {
      name: "Phoenix Suns",
      shortName: "PHX",
      elo: 1778,
    },
    odds: { home: 1.9, away: 1.9 },
    modelProb: { home: 0.55, away: 0.45 },
    pick: "home",
    edgePercent: 2.4,
    confidence: 63,
  },
  {
    id: "basketball-upcoming-2",
    sport: "basketball",
    league: "EuroLeague",
    status: "upcoming",
    startTime: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
    home: {
      name: "Real Madrid",
      shortName: "RMB",
      elo: 1723,
    },
    away: {
      name: "Olympiacos",
      shortName: "OLY",
      elo: 1698,
    },
    odds: { home: 1.7, away: 2.15 },
    modelProb: { home: 0.62, away: 0.38 },
    pick: "home",
    edgePercent: 4.1,
    confidence: 69,
  },
  {
    id: "tennis-upcoming-1",
    sport: "tennis",
    league: "WTA Tour",
    status: "upcoming",
    startTime: new Date(Date.now() + 1.5 * 60 * 60 * 1000).toISOString(),
    home: {
      name: "Iga Swiatek",
      shortName: "SWI",
      elo: 2089,
    },
    away: {
      name: "Aryna Sabalenka",
      shortName: "SAB",
      elo: 2067,
    },
    odds: { home: 1.75, away: 2.05 },
    modelProb: { home: 0.59, away: 0.41 },
    pick: "home",
    edgePercent: 3.5,
    confidence: 67,
  },
  {
    id: "esports-upcoming-1",
    sport: "esports",
    league: "LEC",
    status: "upcoming",
    startTime: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    home: {
      name: "G2 Esports",
      shortName: "G2",
      elo: 1654,
    },
    away: {
      name: "Fnatic",
      shortName: "FNC",
      elo: 1638,
    },
    odds: { home: 1.65, away: 2.2 },
    modelProb: { home: 0.63, away: 0.37 },
    pick: "home",
    edgePercent: 2.8,
    confidence: 64,
  },
  {
    id: "baseball-upcoming-1",
    sport: "baseball",
    league: "MLB",
    status: "upcoming",
    startTime: new Date(Date.now() + 7 * 60 * 60 * 1000).toISOString(),
    home: {
      name: "New York Yankees",
      shortName: "NYY",
      elo: 1612,
    },
    away: {
      name: "Boston Red Sox",
      shortName: "BOS",
      elo: 1589,
    },
    odds: { home: 1.8, away: 2.0 },
    modelProb: { home: 0.56, away: 0.44 },
    pick: "home",
    edgePercent: 1.9,
    confidence: 58,
  },

  // Finished matches
  {
    id: "soccer-finished-1",
    sport: "soccer",
    league: "Serie A",
    status: "finished",
    startTime: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    home: {
      name: "Inter Milan",
      shortName: "INT",
      elo: 1856,
    },
    away: {
      name: "AC Milan",
      shortName: "ACM",
      elo: 1823,
    },
    score: { home: 3, away: 1 },
    odds: { home: 1.9, draw: 3.5, away: 3.8 },
    modelProb: { home: 0.52, draw: 0.25, away: 0.23 },
    pick: "home",
    edgePercent: 4.8,
    confidence: 74,
    result: "win",
  },
  {
    id: "basketball-finished-1",
    sport: "basketball",
    league: "NBA",
    status: "finished",
    startTime: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    home: {
      name: "Miami Heat",
      shortName: "MIA",
      elo: 1745,
    },
    away: {
      name: "Milwaukee Bucks",
      shortName: "MIL",
      elo: 1798,
    },
    score: { home: 98, away: 112 },
    odds: { home: 2.3, away: 1.6 },
    modelProb: { home: 0.38, away: 0.62 },
    pick: "away",
    edgePercent: 3.1,
    confidence: 66,
    result: "win",
  },
  {
    id: "tennis-finished-1",
    sport: "tennis",
    league: "ATP Tour",
    status: "finished",
    startTime: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    home: {
      name: "Novak Djokovic",
      shortName: "DJO",
      elo: 2156,
    },
    away: {
      name: "Daniil Medvedev",
      shortName: "MED",
      elo: 2098,
    },
    score: { home: 2, away: 0 },
    odds: { home: 1.5, away: 2.6 },
    modelProb: { home: 0.68, away: 0.32 },
    pick: "home",
    edgePercent: 1.2,
    confidence: 55,
    result: "win",
  },
];
